### ISSUE TITLE
does not work with 0 as starting point

### ISSUE THREAD

**Issue by Maikel1963** [pmqtt/pretty-edit#4]
Hey pmqtt
I like this feature (missed it here, because in the lab we have an expensive ide which has it - but not at home)
Sadly I often have to start numbering with "0" and this does not work
entring 1 works
entering 2;2 works
but 0;1 does not

Aditionally I would like to have the possibility to have leading zeroes (for numbers lower than 9 when entering e.g 1;1 for 32 lines)

**Comment by pmqtt** [comment]
Hey Maikel,
give me two days, to check and fix!

**Comment by pmqtt** [comment]
closed
you can download the new version!
